admins: []
forwards:
- source: -1001404537486
  dest:
  - -1001686184174
  offset: 20414
  end: null
show_forwarded_from: false
live:
  delete_sync: true
  delete_on_edit: null
past:
  delay: 3.0
plugins: {}
