admins: []
forwards:
- source: -1001389499393
  dest:
  - -1001659164529
  offset: 3055
  end: null
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins: {}
